
const GlobalConstants = {
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        BRANCH_ADD_NEW : "BRANCH_ADD_NEW",
        DRIVER_ADD_NEW : "DRIVER_ADD_NEW",
        OFFICER_ADD_NEW : "OFFICER_ADD_NEW",
        ADMIN_ADD_NEW : "ADMIN_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",

    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
        DEFAULT : "",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        BRANCH_DELETE : "BRANCH_DELETE",
        DRIVER_DELETE: "DRIVER_DELETE",
        SHIPMENT_DELETE: "SHIPMENT_DELETE",
        OFFICER_DELETE: "OFFICER_DELETE",
    },
}

const {MODAL_BODY_TYPES, RIGHT_DRAWER_TYPES, CONFIRMATION_MODAL_CLOSE_TYPES} = GlobalConstants
export {MODAL_BODY_TYPES, RIGHT_DRAWER_TYPES, CONFIRMATION_MODAL_CLOSE_TYPES}